# Site settings
title: Tree62
email: info@tree62.nl
url: http://tree62.github.io
description: "Tree62 is een grafisch ontwerpbureau in Amsterdam. Wij zijn gespecialiseerd in het ontwerpen van websites, drukwerk en hele huisstijlen."
intro_text: "Tree62 is cool. En jij kan dat ook zijn."
intro_second_text: "We houden van ontwerp. Heel veel. Tree62 is een grafisch ontwerpbureau in Amsterdam. Wij zijn gespecialiseerd in het ontwerpen van websites, drukwerk en hele huisstijlen."

# Contact form: comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: F3F1DA #80B3FF
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Tree62
  location: Amsterdam
  social: Online
  credits: Akoten

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  # - title: twitter
  #   url: http://twitter.com/jekyllrb
  - title: Facebook
    url: https://www.facebook.com/tree62book?fref=ts
  # - title: stack-overflow
  #   url: http://stackoverflow.com/questions/tagged/jekyll
  # - title: bitbucket
  #   url: http://bitbucket.org/jekyll
  # - title: github
  #   url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: Tree62
  - line: Linnaeusstraat 251 4
  - line: 1093 ER - Amsterdam
  - line:
  - line: KvK 62007025
  # - line: Beverly Hills, CA 90210

# Credits content
credits: 'Tree62 is een grafisch ontwerpbureau uit Amsterdam. Wij zijn gespecialiseerd in het ontwerpen van websites, drukwerk en complete huisstijlen.'

# Build settings
markdown: kramdown
permalink: pretty
